#!/bin/bash
sudo modprobe hci_uart
sleep 2
lsmod
hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
sleep 2
/usr/libexec/bluetooth/bluetoothd &
sleep 2
hciconfig hci0 up
sleep 2
export LIBASOUND_THREAD_SAFE=0
sudo /usr/bin/bluealsa -S &
#sudo bt-device -c 6C:5D:63:21:30:5C #soundBuds


